language: julia

matrix:
  include:
    - os: linux
      dist: focal
      julia: 1.6
    - os: osx
      julia: 1.6

addons:
  apt_packages:
    - gfortran
    - liblapack3
    - liblapack-dev
    - libopenblas-base
    - libopenblas-dev

branches:
  only:
    - master

before_install:
  - if [ `uname` == "Linux" ]; then unset DY_LIBRARY_PATH; fi
  - if [ `uname` == "Darwin" ]; then brew install openblas; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - julia -E 'using Pkg; Pkg.build()'

script:
  - julia --check-bounds=yes -E 'using Pkg; Pkg.test("NLPModelsAlgencan"; coverage=true)'
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl


after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("NLPModelsAlgencan")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

