name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.6'
        os:
          - ubuntu-latest
          - macOS-latest
          # - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v1
      - name: install gfortran and lapack
        run: |
            if ${{ contains(matrix.os, 'ubuntu') }}; then
              sudo apt-get update
              sudo apt-get install --yes build-essential gfortran liblapack3 liblapack-dev libopenblas-base libopenblas-dev
            elif ${{ contains(matrix.os, 'macOS') }}; then
              which gfortran-11
              brew install gcc@11
              ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
              ln -s /usr/local/bin/gcc-11 /usr/local/bin/gcc
              brew install openblas
            fi
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
